spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: liquibase
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/heygarzon}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  liquibase:
    ## See  https://docs.spring.io/spring-boot/api/java/org/springframework/boot/liquibase/autoconfigure/LiquibaseProperties.html for more details
    dropFirst: false
db:
  loadInitialData: false
  dataSqlPath: dbinit/data.sql
